{{ if .Values.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keyvalue-ingress
spec:
  rules:
  - host: keyvalue.com
    http:
      paths:
      - path: /get
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.servicePort }}
      - path: /search
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.servicePort }}
      - path: /set
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.servicePort }}
{{ end }}